// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvOmA2nhVgYSFNrtvmW4LAsCEJJIqUIUo',
    appId: '1:38319402528:web:525c11f9532b7be21d9645',
    messagingSenderId: '38319402528',
    projectId: 'clips-3d14e',
    authDomain: 'clips-3d14e.firebaseapp.com',
    storageBucket: 'clips-3d14e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9NdkzJwXhYPx2GQ7jmeqfihZDt1hHFcs',
    appId: '1:38319402528:android:c914c378773502d91d9645',
    messagingSenderId: '38319402528',
    projectId: 'clips-3d14e',
    storageBucket: 'clips-3d14e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvOhWSz-lwSJRZ7yyNBkHQuia8UTtrRmc',
    appId: '1:38319402528:ios:b0958d75427b821f1d9645',
    messagingSenderId: '38319402528',
    projectId: 'clips-3d14e',
    storageBucket: 'clips-3d14e.appspot.com',
    iosClientId: '38319402528-fa9s6nc2ranjbmss89u4m7p91daqrdi5.apps.googleusercontent.com',
    iosBundleId: 'com.example.clips',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvOhWSz-lwSJRZ7yyNBkHQuia8UTtrRmc',
    appId: '1:38319402528:ios:84af7b8d322d52c51d9645',
    messagingSenderId: '38319402528',
    projectId: 'clips-3d14e',
    storageBucket: 'clips-3d14e.appspot.com',
    iosClientId: '38319402528-55ecel41vcvghge73n8atnsa5hvu8k2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.clips.RunnerTests',
  );
}
